#!/usr/bin/env node
// Generates syntaxes/fmcalc.tmLanguage.json (the .fmcalc TextMate grammar) from the vendored fmscriptinventory
// catalogue (shared/data/fm-calc-catalogue.json), so highlighting follows every catalogue update.
//   node scripts/generate-grammar.mjs           write the grammar
//   node scripts/generate-grammar.mjs --check   fail if the committed grammar is stale (used in CI)
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const vscodeDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const sharedData = join(vscodeDir, '..', 'shared', 'data');
const target = join(vscodeDir, 'syntaxes', 'fmcalc.tmLanguage.json');

const language = JSON.parse(readFileSync(join(sharedData, 'fm-calc-catalogue.json'), 'utf8'));
const functions = language.functions;

const escape = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
// Longest first, so e.g. "GetValue" is not cut short by "Get"
const alternation = (names) => [...new Set(names)].sort((a, b) => b.length - a.length || a.localeCompare(b)).map(escape).join('|');

const functionNames = alternation(functions.map((f) => f.name).filter((n) => n.toLowerCase() !== 'get'));
const constantNames = alternation(language.constants.map((c) => c.name));
const wordOperators = alternation(language.operators.filter((o) => /^[a-z]+$/i.test(o.symbol)).map((o) => o.symbol));

const grammar = {
  $schema: 'https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json',
  name: 'FileMaker Calculation',
  scopeName: 'source.fmcalc',
  comment: 'GENERATED by scripts/generate-grammar.mjs from shared/data. Do not edit by hand.',
  patterns: [{ include: '#expression' }],
  repository: {
    expression: {
      patterns: [
        { include: '#comments' },
        { include: '#strings' },
        { include: '#quoted-names' },
        { include: '#get-call' },
        { include: '#function-calls' },
        { include: '#field-references' },
        { include: '#variables' },
        { include: '#constants' },
        { include: '#numbers' },
        { include: '#operators' },
        { include: '#punctuation' },
      ],
    },
    comments: {
      patterns: [
        { name: 'comment.line.double-slash.fmcalc', match: '//.*$' },
        { name: 'comment.block.fmcalc', begin: '/\\*', end: '\\*/' },
      ],
    },
    strings: {
      name: 'string.quoted.double.fmcalc',
      begin: '"',
      end: '"',
      patterns: [
        { name: 'constant.character.escape.fmcalc', match: '\\\\.' },
        { name: 'constant.character.paragraph.fmcalc', match: '¶' },
      ],
    },
    'quoted-names': {
      comment: '${ } quotes reserved names used as field or table names',
      name: 'variable.other.quoted.fmcalc',
      match: '\\$\\{[^}]*\\}',
    },
    'get-call': {
      comment: 'Get ( ConstantName ): any name is accepted, so the grammar does not depend on a complete list',
      match: '(?i)\\b(Get)\\s*(\\()\\s*([A-Za-z][A-Za-z0-9]*)\\s*(\\))',
      captures: {
        1: { name: 'support.function.builtin.fmcalc' },
        2: { name: 'punctuation.section.arguments.begin.fmcalc' },
        3: { name: 'support.constant.get.fmcalc' },
        4: { name: 'punctuation.section.arguments.end.fmcalc' },
      },
    },
    'function-calls': {
      patterns: [
        {
          comment: 'Built-in functions from shared data (function names are case-insensitive in FileMaker)',
          match: `(?i)\\b(${functionNames})(?=\\s*\\()`,
          name: 'support.function.builtin.fmcalc',
        },
        {
          comment: 'Any other call: custom functions and built-ins not yet in shared data',
          match: '\\b([\\p{L}_][\\p{L}\\p{N}_.]*)(?=\\s*\\()',
          name: 'entity.name.function.fmcalc',
        },
      ],
    },
    'field-references': {
      match: '\\b([\\p{L}_][\\p{L}\\p{N}_.]*)\\s*(::)\\s*([\\p{L}_][\\p{L}\\p{N}_.]*)',
      captures: {
        1: { name: 'entity.name.type.table.fmcalc' },
        2: { name: 'punctuation.accessor.fmcalc' },
        3: { name: 'variable.other.field.fmcalc' },
      },
    },
    variables: {
      patterns: [
        { name: 'variable.other.global.fmcalc', match: '\\$\\$[\\p{L}_~][\\p{L}\\p{N}_.~]*' },
        { name: 'variable.other.local.fmcalc', match: '\\$[\\p{L}_~][\\p{L}\\p{N}_.~]*' },
      ],
    },
    constants: {
      patterns: [
        { name: 'constant.language.fmcalc', match: `(?i)\\b(${constantNames})\\b` },
        { name: 'keyword.operator.logical.fmcalc', match: `(?i)\\b(${wordOperators})\\b` },
      ],
    },
    numbers: {
      name: 'constant.numeric.fmcalc',
      match: '(?<![A-Za-z_$])(?:[0-9]+(?:\\.[0-9]+)?|\\.[0-9]+)(?:[eE][+-]?[0-9]+)?',
    },
    operators: {
      patterns: [
        { name: 'keyword.operator.comparison.fmcalc', match: '≠|≤|≥|<>|<=|>=|=|<|>' },
        { name: 'keyword.operator.arithmetic.fmcalc', match: '[+\\-*/^]' },
        { name: 'keyword.operator.concatenation.fmcalc', match: '&' },
        { name: 'constant.character.paragraph.fmcalc', match: '¶' },
      ],
    },
    punctuation: {
      patterns: [
        { name: 'punctuation.separator.arguments.fmcalc', match: ';' },
        { name: 'punctuation.section.parens.fmcalc', match: '[()]' },
        { name: 'punctuation.section.brackets.fmcalc', match: '[\\[\\]]' },
      ],
    },
  },
};

const json = JSON.stringify(grammar, null, 2) + '\n';
if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(target, 'utf8');
  } catch {}
  if (current !== json) {
    console.error('syntaxes/fmcalc.tmLanguage.json is stale. Run: node scripts/generate-grammar.mjs');
    process.exit(1);
  }
  console.log('Grammar is up to date.');
} else {
  writeFileSync(target, json);
  console.log(`Wrote ${target} (${functions.length} functions, ${language.constants.length} constants)`);
}
